# Generated by Django 2.2.6 on 2019-10-10 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text_for_real_test', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Feature Questions',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('question_attended', models.ManyToManyField(to='OneByOne.Question')),
            ],
            options={
                'verbose_name_plural': 'User Details',
            },
        ),
        migrations.CreateModel(
            name='UserResponsesForFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_1', models.BooleanField(default=False, verbose_name='Feature_1')),
                ('choice_2', models.BooleanField(default=False, verbose_name='Feature_2')),
                ('choice_3', models.BooleanField(default=False, verbose_name='Feature_3')),
                ('choice_4', models.BooleanField(default=False, verbose_name='Feature_4')),
                ('choice_5', models.BooleanField(default=False, verbose_name='Feature_6')),
                ('choice_corr', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='OneByOne.QuestionFeatures')),
                ('user_id', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='OneByOne.UserDetails')),
            ],
            options={
                'verbose_name_plural': 'User Responses for Features',
            },
        ),
        migrations.CreateModel(
            name='UserResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('choice_corr', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='OneByOne.Question')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OneByOne.UserDetails')),
            ],
            options={
                'verbose_name_plural': 'User Responses Set 1',
            },
        ),
        migrations.CreateModel(
            name='ChoiceFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature1_A', models.ImageField(upload_to='images/')),
                ('feature2_A', models.ImageField(upload_to='images/')),
                ('feature1_B', models.ImageField(upload_to='images/')),
                ('feature2_B', models.ImageField(upload_to='images/')),
                ('feature1_C', models.ImageField(upload_to='images/')),
                ('feature2_C', models.ImageField(upload_to='images/')),
                ('feature1_D', models.ImageField(upload_to='images/')),
                ('feature2_D', models.ImageField(upload_to='images/')),
                ('feature1_E', models.ImageField(upload_to='images/')),
                ('feature2_E', models.ImageField(upload_to='images/')),
                ('question_rel', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='OneByOne.Question')),
            ],
            options={
                'verbose_name_plural': 'Feature Choice',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample1_A', models.ImageField(upload_to='images/')),
                ('question', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='OneByOne.Question')),
            ],
            options={
                'verbose_name_plural': 'Choice',
            },
        ),
    ]
