# Generated by Django 2.2.6 on 2019-10-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneByOne', '0002_auto_20191010_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stimuli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stimuli', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Stimuli',
            },
        ),
        migrations.AddField(
            model_name='userdetails',
            name='stimuli_attended',
            field=models.ManyToManyField(to='OneByOne.Stimuli'),
        ),
    ]
