# Generated by Django 2.2.6 on 2019-10-10 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OneByOne', '0004_userdetails_iteration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicefeatures',
            name='question_rel',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='OneByOne.QuestionFeatures'),
        ),
    ]
