# Generated by Django 2.2.6 on 2019-10-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OneByOne', '0005_auto_20191010_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='iteration',
        ),
    ]
