# Generated by Django 2.2.6 on 2019-10-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneByOne', '0006_remove_userdetails_iteration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stimuli',
            name='stimuli',
        ),
        migrations.AddField(
            model_name='stimuli',
            name='stimuli_1',
            field=models.ImageField(default='Contrast00.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='stimuli',
            name='stimuli_10',
            field=models.ImageField(default='Contrast00.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='stimuli',
            name='stimuli_2',
            field=models.ImageField(default='Contrast01.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='stimuli',
            name='stimuli_3',
            field=models.ImageField(default='Contrast02.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='stimuli',
            name='stimuli_4',
            field=models.ImageField(default='Contrast03.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='stimuli',
            name='stimuli_5',
            field=models.ImageField(default='Contrast04.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='stimuli',
            name='stimuli_6',
            field=models.ImageField(default='Contrast00.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='stimuli',
            name='stimuli_7',
            field=models.ImageField(default='Contrast00.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='stimuli',
            name='stimuli_8',
            field=models.ImageField(default='Contrast00.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='stimuli',
            name='stimuli_9',
            field=models.ImageField(default='Contrast00.png', upload_to='images/'),
        ),
    ]
