# Generated by Django 2.2.6 on 2019-10-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneByOne', '0007_auto_20191013_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stimuli',
            name='stimuli_1',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='stimuli',
            name='stimuli_10',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='stimuli',
            name='stimuli_2',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='stimuli',
            name='stimuli_3',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='stimuli',
            name='stimuli_4',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='stimuli',
            name='stimuli_5',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='stimuli',
            name='stimuli_6',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='stimuli',
            name='stimuli_7',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='stimuli',
            name='stimuli_8',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='stimuli',
            name='stimuli_9',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
