# Generated by Django 2.2.6 on 2019-10-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OneByOne', '0008_auto_20191013_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='stimuli_attended',
        ),
    ]
