# Generated by Django 2.2.6 on 2019-10-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OneByOne', '0009_remove_userdetails_stimuli_attended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stimuli',
            old_name='stimuli_1',
            new_name='stimuli',
        ),
        migrations.RemoveField(
            model_name='stimuli',
            name='stimuli_10',
        ),
        migrations.RemoveField(
            model_name='stimuli',
            name='stimuli_2',
        ),
        migrations.RemoveField(
            model_name='stimuli',
            name='stimuli_3',
        ),
        migrations.RemoveField(
            model_name='stimuli',
            name='stimuli_4',
        ),
        migrations.RemoveField(
            model_name='stimuli',
            name='stimuli_5',
        ),
        migrations.RemoveField(
            model_name='stimuli',
            name='stimuli_6',
        ),
        migrations.RemoveField(
            model_name='stimuli',
            name='stimuli_7',
        ),
        migrations.RemoveField(
            model_name='stimuli',
            name='stimuli_8',
        ),
        migrations.RemoveField(
            model_name='stimuli',
            name='stimuli_9',
        ),
    ]
