# Generated by Django 2.2.6 on 2020-02-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneByOne', '0012_auto_20191030_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
