# Generated by Django 2.2.6 on 2020-02-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneByOne', '0013_userdetails_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponsesforfeatures',
            name='choice_6',
            field=models.BooleanField(default=False, verbose_name='Color for classification'),
        ),
        migrations.AddField(
            model_name='userresponsesforfeatures',
            name='choice_7',
            field=models.BooleanField(default=False, verbose_name='None of the above'),
        ),
        migrations.AlterField(
            model_name='userresponsesforfeatures',
            name='choice_1',
            field=models.BooleanField(default=False, verbose_name='Lower Fin'),
        ),
        migrations.AlterField(
            model_name='userresponsesforfeatures',
            name='choice_2',
            field=models.BooleanField(default=False, verbose_name='Tail'),
        ),
        migrations.AlterField(
            model_name='userresponsesforfeatures',
            name='choice_3',
            field=models.BooleanField(default=False, verbose_name='Upper Fin'),
        ),
        migrations.AlterField(
            model_name='userresponsesforfeatures',
            name='choice_4',
            field=models.BooleanField(default=False, verbose_name='Body Fin'),
        ),
        migrations.AlterField(
            model_name='userresponsesforfeatures',
            name='choice_5',
            field=models.BooleanField(default=False, verbose_name='Mouth'),
        ),
    ]
