# Generated by Django 2.2.6 on 2020-02-10 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OneByOne', '0014_auto_20200210_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponsesForDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('user_id', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='OneByOne.UserDetails')),
            ],
            options={
                'verbose_name_plural': 'User Responses for Description',
            },
        ),
    ]
